name: Concurrency Demo

on: [workflow_dispatch]

concurrency:
  group: sample-concurrency-group
  cancel-in-progress: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 1 is running"