name: Deploy to an environment

on:
  workflow_call:
    inputs:
      environment:
        description: The environment to deploy to
        required: true
        type: string
      
      artifact-name:
        description: The name of the artifact to download
        required: true
        type: string

jobs:
  deploy-job:
    name: Deploy to ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
        
      - name: Deploy app
        run: cat ${{ inputs.artifact-name }}.txt

      - name: Log in to Azure
        if: inputs.environment == 'Prod'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show Azure resources
        if: inputs.environment == 'Prod'
        run: |
          az account show
          az group list

      - name: Use environment secret
        run: |
          echo ${{ secrets.ENV_SECRET }} | base64
          echo
          echo To check the secret value, base64-decode it