name: Use reusable workflow

on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: Who to greet
        type: string
        default: world

jobs:
  job-in-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Before switching to reusable workflow
        run: echo "This is before the reusable workflow"

  call-reusable:
    needs: job-in-workflow
    uses: ReneSchumacher/reusable-workflows/.github/workflows/sample-reusable-workflow.yml@main
    with:
      target-runner: ubuntu-latest
      who-to-greet: ${{ inputs.who-to-greet }}

  job2-in-workflow:
    runs-on: ubuntu-latest
    needs: call-reusable
    steps:
      - name: After coming back from reusable workflow
        run: echo "This is after the reusable workflow"
    